version: '3.2'

services:
  mongo:
    image: mongo:4.2.10
    restart: always
    ports:
      - '27017:27017'
    networks:
      - digital-stage

  digital-server:
    image: digital-server:0.0.1
    build: .
    init: true
    depends_on:
      - mongo
    restart: always
    environment:
      MONGO_URL: 'mongodb://mongo:27017'
      PORT: '4000'
    ports:
      - '4000:4000'
    networks:
      - digital-stage

networks:
  digital-stage:
